from config.constants import LOCAL_MODELS_PREFIX
from utils.dataclasses import Task


_BERT_BASE = "bert-base-uncased"
_ROBERTA_BASE = "FacebookAI/roberta-base"
_DISTILBERT_BASE = "distilbert/distilbert-base-uncased"
_LLAMA_MODEL = f"{LOCAL_MODELS_PREFIX}/meta-llama/Llama-2-7b-hf"
_MISTRAL_MODEL = f"{LOCAL_MODELS_PREFIX}/mistralai/Mistral-7B-v0.1"


IMDB_TASK: Task = Task(
    dataset_name = "imdb",
    dataset_train = "train",
    dataset_val = "train",
    dataset_test = "test",
    dataset_column_text = "text",
    dataset_column_label = "label",
    bert_fine_tuned_model = "textattack/bert-base-uncased-imdb",
    roberta_fine_tuned_model = "textattack/roberta-base-imdb",
    distilbert_fine_tuned_model = "textattack/distilbert-base-uncased-imdb",
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    is_llm_set_max_len = True,
    llm_explained_tokenizer_max_length = 400,
    llm_interpreter_tokenizer_max_length = 425,
    bert_base_model = _BERT_BASE,
    labels_str_int_maps = dict(negative = "N", positive = "P"),
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = 2_000,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "imdb",
    paper_name = "IMDB",
    hp_search_n_trials = 30,
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    is_finetuned_with_lora = False,
    llm_task_prompt = "Classify the sentiment of the movie review. For each review the label is positive (P) or negative (N).",
    llm_few_shots_prompt = [
        (
            "This movie is so bad, I knew how it ends right after this little girl killed the first person. Very bad acting very bad plot very bad movie. Do yourself a favour and don't watch it.",
            "N",
        ),
        (
            "Very smart, sometimes shocking, I just love it. The movie captivates your attention for every second.",
            "P",
        ),
        (
            "If there is a movie to be called perfect then this is it. Whatever you do, do not miss it.",
            "P",
        ),
        ("Long, boring, blasphemous. Never have I been so glad to see ending credits roll.", "N"),
    ],
)


EMOTION_TASK: Task = Task(
    dataset_name = "emotion",
    dataset_train = "train",
    dataset_val = "validation",
    dataset_test = "test",
    dataset_column_text = "text",
    dataset_column_label = "label",
    bert_fine_tuned_model = "bhadresh-savani/bert-base-uncased-emotion",
    roberta_fine_tuned_model = "bhadresh-savani/roberta-base-emotion",
    distilbert_fine_tuned_model = "Rahmat82/DistilBERT-finetuned-on-emotion",
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    bert_base_model = _BERT_BASE,
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    is_finetuned_with_lora = False,
    labels_str_int_maps = dict(
        sadness = "A",
        joy = "B",
        love = "C",
        anger = "D",
        fear = "E",
        surprise = "F",
    ),
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = None,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "emotion",
    paper_name = "Emotion",
    hp_search_n_trials = 30,
    llm_task_prompt = (
        "Classify the emotion expressed in each sentence. "
        "Use sadness (A), joy (B), love (C), anger (D), fear (E), or surprise (F)."
    ),
    llm_few_shots_prompt = [
        ("I feel devastated after hearing the news.", "A"),
        ("I am thrilled that everything worked out.", "B"),
        ("I adore how thoughtful that gesture was.", "C"),
        ("I am furious about how unfair this is.", "D"),
        ("I am scared that something bad is about to happen.", "E"),
        ("I was shocked when I saw the result.", "F"),
    ],
)


SST2_TASK: Task = Task(
    dataset_name = "sst2",
    dataset_train = "train",
    dataset_val = "validation",
    dataset_test = "validation",
    dataset_column_text = "sentence",
    dataset_column_label = "label",
    bert_fine_tuned_model = "textattack/bert-base-uncased-SST-2",
    roberta_fine_tuned_model = "textattack/roberta-base-SST-2",
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    is_finetuned_with_lora = False,
    labels_str_int_maps = dict(negative = "N", positive = "P"),
    distilbert_fine_tuned_model = "distilbert-base-uncased-finetuned-sst-2-english",
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    bert_base_model = _BERT_BASE,
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = None,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "sst2",
    paper_name = "SST-2",
    hp_search_n_trials = 30,
    llm_task_prompt = "Classify the sentiment of the sentence. The label is positive (P) or negative (N).",
    llm_few_shots_prompt = [
        ("hide new secretions from the parental units", "N"),
        ("the greatest musicians", "P"),
        ("are more deeply thought through than in most right-thinking films", "P"),
        ("on the worst revenge-of-the-nerds cliches the filmmakers could dredge up", "N"),
    ],
)


ERASER_MOVIE_REVIEWS_TASK: Task = Task(
    dataset_name = "eraser_movie_reviews",
    dataset_train = "train",
    dataset_val = "validation",
    dataset_test = "test",
    dataset_column_text = "text",
    dataset_column_label = "label",
    bert_fine_tuned_model = None,
    roberta_fine_tuned_model = None,
    distilbert_fine_tuned_model = None,
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    is_llm_set_max_len = True,
    llm_explained_tokenizer_max_length = 400,
    llm_interpreter_tokenizer_max_length = 425,
    bert_base_model = _BERT_BASE,
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    labels_str_int_maps = dict(negative = "N", positive = "P"),
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = None,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "eraser_movie_reviews",
    paper_name = "ERASER Movie Reviews",
    is_finetuned_with_lora = False,
    hp_search_n_trials = 30,
    llm_task_prompt = "Classify the sentiment of the movie review. The label is positive (P) or negative (N).",
    llm_few_shots_prompt = [
        ("The story drags and the performances never become convincing.", "N"),
        ("A funny, heartfelt film with memorable performances.", "P"),
        ("The script is dull and the movie collapses by the final act.", "N"),
        ("An engaging review target with warmth, humor, and energy.", "P"),
    ],
)


ROTTEN_TOMATOES_TASK: Task = Task(
    dataset_name = "rotten_tomatoes",
    dataset_train = "train",
    dataset_val = "validation",
    dataset_test = "test",
    dataset_column_text = "text",
    dataset_column_label = "label",
    bert_fine_tuned_model = "textattack/bert-base-uncased-rotten-tomatoes",
    roberta_fine_tuned_model = "textattack/roberta-base-rotten-tomatoes",
    distilbert_fine_tuned_model = "textattack/distilbert-base-uncased-rotten-tomatoes",
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    bert_base_model = _BERT_BASE,
    is_finetuned_with_lora = False,
    labels_str_int_maps = dict(negative = "N", positive = "P"),
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = None,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "rotten_tomatoes",
    paper_name = "Rotten Tomatoes",
    hp_search_n_trials = 30,
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    llm_task_prompt = "Classify the sentiment of the sentence. The label is positive (P) or negative (N).",
    llm_few_shots_prompt = [
        ("the film desperately sinks further and further into comedy futility.", "N"),
        ("if you like going to the movies to have fun, this is a good place to start.", "P"),
        ("plays like the old disease-of-the-week small-screen melodramas.", "N"),
        ("hip-hop has a history, and it is a metaphor for this love story.", "P"),
        ("so exaggerated and broad that it comes off as annoying rather than charming.", "N"),
    ],
)


AGN_TASK: Task = Task(
    dataset_name = "ag_news",
    dataset_train = "train",
    dataset_val = "train",
    dataset_test = "test",
    dataset_column_text = "text",
    dataset_column_label = "label",
    bert_fine_tuned_model = "fabriceyhc/bert-base-uncased-ag_news",
    roberta_fine_tuned_model = "textattack/roberta-base-ag-news",
    labels_str_int_maps = dict(world = "A", sports = "B", business = "C", sci_tech = "D"),
    distilbert_fine_tuned_model = f"{LOCAL_MODELS_PREFIX}/TRAINED_MODELS/agn_distillbert",
    default_lr = 4e-5,
    llm_lr = 8e-5,
    test_sample = 2_000,
    train_sample = 1_000,
    hp_search_test_sample = 200,
    hp_search_train_sample = 450,
    name = "agn",
    paper_name = "AG News",
    hp_search_n_trials = 30,
    llama_model = _LLAMA_MODEL,
    mistral_model = _MISTRAL_MODEL,
    llm_task_prompt = "Classify the news article. The label is World (A), Sports (B), Business (C), or Sci/Tech (D).",
    roberta_base_model = _ROBERTA_BASE,
    distilbert_base_model = _DISTILBERT_BASE,
    bert_base_model = _BERT_BASE,
    llama_adapter = f"{LOCAL_MODELS_PREFIX}/TRAINED_MODELS/LLAMA_agn_is_bf16_True_is_use_prompt_False",
    mistral_adapter = f"{LOCAL_MODELS_PREFIX}/TRAINED_MODELS/MISTRAL_agn_is_bf16_True_is_use_prompt_False",
    is_finetuned_with_lora = True,
    llm_few_shots_prompt = [],
    is_legacy_task = True,
)


# Backward-compatible symbol aliases used across the local AML copy.
SST_TASK = SST2_TASK
RTN_TASK = ROTTEN_TOMATOES_TASK
